keys:
  - &hosts:
    - &lelia age1w7y8sznrsch9088nq2xmyf782nk98qd6rx2q04utt6fuq8rwq5wsluvsjm
  - &users:
    - &repo age172m87hgekagmx476hh2uuu4xpn2657rsrmascqu6per3qq56f3ssd89tgu
    - &joao 724A264781B08135FE89E9FDBE4D78290B7222EA

creation_rules:
  - path_regex: secrets.json$
    key_groups:
      - pgp:
          - *joao

  - path_regex: nixos/users/.*/secrets.json$
    key_groups:
      - age:
          - *repo
          - *lelia

  - path_regex: nixos/hosts/lelia/secrets.json$
    key_groups:
      - age:
          - *repo
          - *lelia
