keys:
  - &hosts:
    - &lelia 887556E0517635509C7DD736059FFB306AD26DCB
  - &users:
    - &joao 724A264781B08135FE89E9FDBE4D78290B7222EA

creation_rules:
  - path_regex: secrets.json$
    key_groups:
      - pgp:
          - *joao

  - path_regex: sops/hosts/master.json$
    key_groups:
      - pgp:
          - *joao

  - path_regex: sops/hosts/lelia.json$
    key_groups:
      - pgp:
          - *joao
          - *lelia

  - path_regex: sops/users/.*.json$
    key_groups:
      - pgp:
          - *joao
          - *lelia
