# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nixfmt]
command = "nix"
options = ["run", "nixpkgs#nixfmt"]
includes = ["*.nix"]

[formatter.prettier]
command = "nix"
options = ["run", "nixpkgs#nodePackages.prettier", "--", "--write"]
includes = ["*.json", "*.lock", "*.yml", "*.yaml"]
