# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.alejandra]
command = 'nix'
includes = ['*.nix']
options = ['run', 'nixpkgs#alejandra']

[formatter.prettier]
command = 'nix'
includes = ['*.json', '*.yml', '*.yaml', 'flake.lock']
options = ['run', 'nixpkgs#nodePackages.prettier', '--', '--write']
