# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.json", "*.lock", "*.yml", "*.yaml"]
