# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nixfmt]
command = 'nix'
includes = ['*.nix']
options = ['run', 'nixpkgs#alejandra']

[formatter.prettier]
command = 'nix'
includes = ['*.json', '*.lock', '*.yml', '*.yaml']
options = ['run', 'nixpkgs#nodePackages.prettier', '--', '--write']
